# -*- coding: utf-8 -*-
"""Flipkart Web Scrapper Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YS_EB1Ot96MBfx8aTEI0VuJFnqHYclQ1
"""

!pip install bs4
import pandas as pd
import requests
from bs4 import BeautifulSoup

Product_name = []
prices = []
Product_Description = []
Reviews = []

# increase the range to get more pages data
for i in range(2,10):
  url = "https://www.flipkart.com/search?q=mobile+phone+under+50000&sid=tyy%2C4io&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_24_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_24_na_na_na&as-pos=1&as-type=RECENT&suggestionId=mobile+phone+under+50000%7CMobiles&requestId=b87cb666-ecc3-499a-a29f-d0b699912e93&as-searchtext=mobile+phone+under+50000&page="+str(i)

  r = requests.get(url)

  soup = BeautifulSoup(r.text, "lxml")

  # to get only a particular portion of the page
  box = soup.find("div", class_ = "_1YokD2 _3Mn1Gg")

  # soup.find("ANCHOR","CLASS").get("href")
  np = soup.find("a", class_ = "_1LKTO3").get("href")

  # in "np" , we were getting half link only
  # to get the complete link of the next page

  cnp = "https://www.flipkart.com"+np


  # scraping product names
  names = box.find_all("div", class_ = "_4rR01T")
  for i in names:
      # creating a variable and storing our text name
      name = i.text
      # appending that text into our list
      Product_name.append(name)
  # scraping product prices
  prices_in_page = box.find_all("div", class_ = "_30jeq3 _1_WHN1")
  for i in prices_in_page:
    price = i.text
    prices.append(price)
  # scraping product description
  desc = box.find_all("ul", class_ = "_1xgFaf")
  for i in desc:
    description = i.text
    Product_Description.append(description)
  # scraping product ratings
  review = box.find_all("div", class_ = "_3LWZlK")
  for i in review:
    rating = i.text
    Reviews.append(rating)


# creating a DataFrame & storing our lists in it
df = pd.DataFrame({"Product Name": Product_name,
                   "Prices": prices,
                   "Product Description" : Product_Description,
                   "Product Ratings" : Reviews })
# downloading the csv files
from google.colab import files
df.to_csv('flipkart-mobile-data.csv', encoding = 'utf-8-sig')
files.download('flipkart-mobile-data.csv')

